name: Auto-Build-Openwrtx64
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5
      
env:
  rc_rclone: ${{ secrets.RCONFIG }}
  OP_URL: http://drive.google.xggcp.tk/dl/OpenWrt.zip
  OP_NAME: lede
  REPO_NAME: openwrt
  CONFIG_FILE: x64.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo mkdir -p /home/runner/.config/rclone
        sudo cat > rclone.conf << EOF
          ${rc_rclone}
        EOF
        sudo mkdir -p /mnt/gdrive
        sudo cp rclone.conf /home/runner/.config/rclone/  
        sudo rm -rf /home/runner/work/openwrt-CI/openwrt-CI/rclone.conf
        sudo rclone mount GD: /mnt/gdrive --copy-links --allow-other --allow-non-empty --umask 000 --daemon &
        sudo df -TH
    - name: Download openwrt
      run: | 
        wget  $OP_URL
        mkdir -p $OP_NAME
        unzip -d $OP_NAME OpenWrt.zip 
        mv $OP_NAME $REPO_NAME
        sudo rm -rf OpenWrt.zip
    - name: Upload GD ipk
      working-directory: ./openwrt
      run: |
       cd packages/*
       sudo tar czvf x64-ipk-`date +%Y年%m月%d日%H时%M分%S秒`.tar.gz *  
       tmp=$(find . -name "*.tar.gz")
       echo $tmp
       sudo rclone sync $tmp GD:ipk     
    - name: Upload GD x64-bin
      working-directory: ./openwrt
      run: |
       cd targets/*/*
       rm -rf packages
       sudo tar czvf x64-bin-`date +%Y年%m月%d日%H时%M分%S秒`.tar.gz *  
       tmp=$(find . -name "*.tar.gz")
       echo $tmp
       sudo rclone sync $tmp GD:bin  
