name: demo测试
on: 
  release:
    types: [published]
  push:
   branches: 
     - master
  schedule:
     - cron: 0 21 * * 5
  
  watch:
    types: [started]
env:
  rc_rclone: ${{ secrets.RCONFIG }}
  REPO_URL: ${{ secrets.URL}}
  REPO_BRANCH: master
  REPO_NAME: openwrt
  CONFIG_FILE: N1.config
  DIY_SH: ${{ secrets.DIY_SH }}
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
       docker rmi `docker images -q`
       sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc
       sudo -E apt-get -qq update
       sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
       sudo -E apt-get -qq autoremove --purge
       sudo -E apt-get -qq clean
       sudo timedatectl set-timezone "$TZ"
    - name: Configure rclone
      run: |
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo mkdir -p /home/runner/.config/rclone
        sudo cat > rclone.conf << EOF
          ${rc_rclone}
        EOF
        sudo mkdir -p /mnt/gdrive
        sudo cp rclone.conf /home/runner/.config/rclone/  
        sudo rm -rf ~/work/Auto-Build-Openwrt/Auto-Build-Openwrt/rclone.conf
        sudo rclone mount GD: /mnt/gdrive --copy-links --allow-other --allow-non-empty --umask 000 --daemon & 
        df -h
    - name: Clone source code
      run: | 
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH $REPO_NAME
         git clone https://github.com/Lienol/openwrt-package $REPO_NAME/package/lintelstm
         git clone https://github.com/jerrykuku/lua-maxminddb $REPO_NAME/package/lintelstm/lienol/lua-maxminddb
         git clone https://github.com/jerrykuku/luci-app-vssr $REPO_NAME/package/lintelstm/lienol/luci-app-vssr
         rm -rf $REPO_NAME/package/lintelstm/lienol/luci-app-passwall
         git clone https://github.com/kenzok8/openwrt-packages $REPO_NAME/package/lintelstm/path
         mv $REPO_NAME/package/lintelstm/path/* $REPO_NAME/package/lintelstm/lienol
         rm -rf $REPO_NAME/package/lintelstm/path
    - name: Update & Install feeds
      run: |
        cd $REPO_NAME 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        sudo cat > diy.sh << EOF
          ${DIY_SH}
        EOF
    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
      env:
       TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
       TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} 
