name: demo-ssh
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5
    
env:
  rc_rclone: ${{ secrets.RCONFIG }}
  REPO_URL: ${{ secrets.URLS}}
  REPO_BRANCH: master
  REPO_NAME: openwrt
  CONFIG_FILE: x64.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai
  
jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
       echo "Free space:"
       df -h  
       
    - name: Configure rclone
      run: |
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo mkdir -p /home/runner/.config/rclone
        sudo cat > rclone.conf << EOF
          ${rc_rclone}
        EOF
        sudo mkdir -p /mnt/gdrive
        sudo cp rclone.conf /home/runner/.config/rclone/  
        sudo rm -rf ~/work/Auto-Build-Openwrt/Auto-Build-Openwrt/rclone.conf
        sudo rclone mount gd: /mnt/gdrive --copy-links --allow-other --allow-non-empty --umask 000 --daemon & 
        df -h
    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
      env:
       TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
       TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

