name: Auto-Build-OpenwrtN1
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_NAME: openwrt
  CONFIG_FILE: N1.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
       docker rmi `docker images -q`
       sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
       sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
       sudo -E apt-get update
       sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
       sudo -E apt-get -y autoremove --purge
       sudo -E apt-get clean
       sudo timedatectl set-timezone "$TZ"
    - name: Configure rclone
      run: |
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo mkdir -p /home/runner/.config/rclone
        sudo cat > rclone.conf << EOF
         ${rc_rclone}   
        EOF
        sudo mkdir -p /mnt/gdrive
        sudo cp rclone.conf /home/runner/.config/rclone/  
        sudo rm -rf ~/work/Auto-Build-Openwrt/Auto-Build-Openwrt/rclone.conf
        sudo rclone mount GD: /mnt/gdrive --copy-links --allow-other --allow-non-empty --umask 000 --daemon &
    - name: Clone source code
      env: 
       REPO_URL: https://github.com/coolsnowwolf/lede
       REPO_BRANCH: master
       REPO_NAME: openwrt
      run: | 
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH $REPO_NAME

    - name: Update & Install feeds
      run: |
        cd $REPO_NAME 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Configuration Customization - Build_N1
      run: |
        chmod +x $DIY_SH
        [ -e files ] && mv files $REPO_NAME/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $REPO_NAME/.config
        cd $REPO_NAME
        make defconfig
    - name: Download package
      run: |
        cd $REPO_NAME
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      run: |
        cd $REPO_NAME
        make -j$(nproc) || make -j8 V=s
    - name: img packaging
      run: | 
         git clone https://github.com/tuanqing/mknop
         cd mknop
         cp ../$REPO_NAME/bin/targets/*/*/*.tar.gz openwrt
         sudo ./gen_openwrt -d -s 880 -k latest
         devices=("phicomm-n1" "vplus" "beikeyun" "l1pro" "s905x3")
          cd out
          for x in ${devices[*]}; do
            cd $x
            filename=$(ls | awk -F '.img' '{print $1}')
            gzip *.img
            cd ../
            echo "firmware_$x=$filename" >> $GITHUB_ENV
          done
    - name: Upload firmware @ phicomm n1
      uses: actions/upload-artifact@main
      with:
       name: ${{ env.firmware_phicomm-n1 }}
       path: out/phicomm-n1 
    - name: Upload GD N1-img
      run: |
        cd mknop/out/phicomm-n1
        tmp=$(find . -name "*.img")
        echo $tmp
        sudo rclone sync $tmp GD:bin 
    - name: Upload GD packages
      run: |
        cd $REPO_NAME/bin/packages/*
        sudo tar czvf N1-packages-`date +%Y年%m月%d日%H时%M分%S秒`.tar.gz * 
        tmp=$(find . -name "*.tar.gz")
        echo $tmp
        sudo rclone sync $tmp GD:ipk
        
    - name: Upload GD N1-bin
      run: |
        cd $REPO_NAME/bin/targets/*/*
        rm -rf packages
        rm -rf openwrt-armvirt-64-default-rootfs.tar.gz
        sudo tar czvf N1-bin-`date +%Y年%m月%d日%H时%M分%S秒`.tar.gz *  
        tmp=$(find . -name "*.tar.gz")
        echo $tmp
        sudo rclone sync $tmp GD:bin 
        
