name: Auto-Build-OpenwrtN1
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5
      
env:
    rc_rclone: ${{ secrets.RCONFIG }}
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    REPO_NAME: openwrt
    CONFIG_FILE: N1.config
    DIY_SH: diy.sh
    SSH_ACTIONS: false
    UPLOAD_BIN_DIR: false
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    TZ: Asia/Shanghai
 
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
         docker rmi `docker images -q`
         sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
         sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
         sudo -E apt-get update
         sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
         sudo -E apt-get -y autoremove --purge
         sudo -E apt-get clean
         sudo timedatectl set-timezone "$TZ"
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
